name: autoblack
on: [push, pull_request]
jobs:
  Format_Black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --check .
      - name: Commit black formatted changes
        if: failure()
        run: |
          black .
          git config --global user.name 'autoblack'
          git config --global user.email 'autoblack@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_TK }}@github.com/${{ github.repository }}
          git commit -am "lint: Format Python code with Black"
          git push
